CREATE TABLE DEPARTMENT (
    ID int,
    NAME varchar(255),
    LOCATION  varchar(255),
    PRIMARY KEY (ID),
    UNIQUE (ID)
);
CREATE TABLE EMPLOYEE (
    ID int,
    NAME varchar(255),
    SALARY  int,
    DEPT_ID int,
    PRIMARY KEY (ID),
    UNIQUE (ID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID)
);
