INSERT INTO DEPARTMENT (NAME, LOCATION)
VALUES ('Executive','Sydney');
INSERT INTO DEPARTMENT (NAME, LOCATION)
VALUES ('Production','Sydney');
INSERT INTO DEPARTMENT (NAME, LOCATION)
VALUES ('Resources','Cape Town');
INSERT INTO DEPARTMENT (NAME, LOCATION)
VALUES ('Technical','Texas');
INSERT INTO DEPARTMENT (NAME, LOCATION)
VALUES ('Management','Paris');

INSERT INTO EMPLOYEE (NAME, SALARY, DEPT_ID)
VALUES ('Candice','4685', '1');
INSERT INTO EMPLOYEE (NAME, SALARY, DEPT_ID)
VALUES ('Julia','2559', '2');
INSERT INTO EMPLOYEE (NAME, SALARY, DEPT_ID)
VALUES ('Bob','4405', '4');
INSERT INTO EMPLOYEE (NAME, SALARY, DEPT_ID)
VALUES ('Scarlet','2350', '1');
INSERT INTO EMPLOYEE (NAME, SALARY, DEPT_ID)
VALUES ('Ileana','1151', '4');